# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
trigger:
- main
pool:
  vmImage: ubuntu-latest
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'
- task: Npm@1
  displayName: 'Installing Modules in /frontend'
  inputs:
    command: 'install'
    workingDir: 'frontend'
- task: Npm@1
  displayName: 'Installing Modules in /backend'
  inputs:
    command: 'install'
    workingDir: 'backend'
- task: Npm@1
  displayName: 'Build modules in /client'
  inputs:
    command: 'custom'
    workingDir: 'frontend'
    customCommand: 'run build'

    - task: CopyFiles@2
  inputs:
    Contents: |
      frontend/build/**
      backend/**
    TargetFolder: $(Build.ArtifactStagingDirectory)
    
# Step 5: Move frontend build output to site/wwwroot
- task: CopyFiles@2
  displayName: 'Copy frontend build output to site/wwwroot'
  inputs:
    Contents: |
      frontend/build/**
    TargetFolder: $(Build.ArtifactStagingDirectory)/site/wwwroot

# Step 6: Copy backend files to site/wwwroot/backend (if needed)
- task: CopyFiles@2
  displayName: 'Copy backend files to site/wwwroot/backend'
  inputs:
    Contents: |
      backend/**
    TargetFolder: $(Build.ArtifactStagingDirectory)/site/wwwroot/backend

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'release'
    publishLocation: 'Container'
